behaviors:
  SeekerAgentV2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      memory:
        type: replay
        memory_size: 100
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.5
      curiosity:
        gamma: 0.99
        strength: 1
        encoding_size: 64
        learning_rate: 0.001
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 2000